import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router';

const PublicPage = () => {

    const router = useRouter()

  return (
    <>
         <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=" h-100%">
            <header className="border-b-2 border-gray-600">
                <h1 className="text-3xl font-bold">Welcome to <span className="nowrap">Dan D. Repairs!</span></h1>
            </header>
            
            <main className="   ">
                <p className="my-6">Located in Beautiful Downtown Foo City, Dan D. Repairs  provides a trained staff ready to meet your tech repair needs.</p>
                <address className="">
                    Dan D. Repairs<br />
                    555 Foo Drive<br />
                    Foo City, CA 12345<br />
                    <a href="tel:+15555555555">(555) 555-5555</a>
                </address>
                <br />
                <p>Owner: Dan Davidson</p>
                
            </main>
            
            
        </section>
      
    </>
  )
}

export default PublicPage
