import Head from 'next/head'
import PublicPage from '../components/PublicPage'
import Layout from '../components/Layout'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <main className=" h-screen bg-gray-100 px-5 py-2">
        <PublicPage />
        

      </main>
      </Layout>
      
    </div>
  )
}
